#!/usr/bin/perl
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# badmin: A PERL CGI script to administrate BSE banknotes system                        #
# Author: Hristo Grigorov <hgrigorov@gmail.com>                                         #
# Copyright (c) 2011-2012 Busoft Engineering. All right reserved.                       #
# ------------------------------------------------------------------------------------- #
# badmin: back-office user crud and user access control                                 #
# Author: Kaloyan Krastev <kaloyansen@gmail.com>                                        #
# Copyright (c) 2022-2023 Busoft Engineering. All right reserved.                       #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
use strict; 
use warnings;
use CGI;
use DBH;
use Socket;
use CGI::Carp qw/fatalsToBrowser warningsToBrowser/;
use CGI::Session qw/-ip-match/;
use HTML::Template;
use constant ACTION_LOGIN => '_login';
use constant ACTION_LOGOUT => '_logout';
use constant ACTION_USER_PASSWORD => 'modify';
use constant ACTION_USER_ACCESS => 'save';
use constant ACTION_USER_DELETE => 'delete';
use constant ACTION_USER_CREATE => 'create';
use constant ACTION_USER_DETAIL => 'detail';
use constant ACTION_USER_TABLE => 'table';
use constant ACTION_DBUPDATE => '_dbupform';
use constant ACTION_DBUPDATE_SUBMIT => '_dbupsub';
use constant ACTION_FUPDATE => '_flupdate';
use constant ACTION_FUPDATE_SUBMIT => '_flupsub';
use constant ACTION_PRODUCT => '_product';


################################################################################
# front-end static templates
################################################################################

my $PAGE_TOP = HTML::Template->new(filename => 'tmpl/page_top_admin.tmpl');
my $PAGE_MSG = HTML::Template->new(filename => 'tmpl/page_msg_admin.tmpl');
my $PAGE_LOGIN = HTML::Template->new(filename => 'tmpl/page_login_admin.tmpl');
my $PAGE_LOGOUT = HTML::Template->new(filename => 'tmpl/page_logout.tmpl');
my $PAGE_BOTTOM = HTML::Template->new(filename => 'tmpl/page_bottom_admin.tmpl');
my $PAGE_FUPDATE = HTML::Template->new(filename => 'tmpl/page_fupdate.tmpl');
my $PAGE_PRODUCT = HTML::Template->new(filename => 'tmpl/page_product_admin.tmpl');
my $PAGE_DBUPDATE = HTML::Template->new(filename => 'tmpl/page_dbupdate.tmpl');
my $PAGE_TABLE = HTML::Template->new(filename => 'tmpl/page_table.tmpl');
my $PAGE_USER = HTML::Template->new(filename => 'tmpl/page_user.tmpl');
# my $PAGE_USERS = HTML::Template->new(filename => 'tmpl/page_users_admin.tmpl');


################################################################################
# MAIN FUNCTION                                                                
################################################################################

DBH::db_connect(); # powered by DBH.pm

$CGI::POST_MAX = 1024 * 20000; # Limit upload to 20MB
my $cgi = new CGI;
#my $session = new CGI::Session("serializer:freezethaw", $cgi, {Directory=>'/tmp'}) or die CGI::Session->errstr;
my $session = new CGI::Session(undef, $cgi, {Directory=>'/tmp'}) or die CGI::Session->errstr;
my $cookie = $cgi->cookie(CGISESSID => $session->id );
#my $cookie = $cgi->cookie( -name => $session->name, -value => $session->id );

print $cgi->header(-charset => 'utf-8', -cookie=>$cookie);
#print $session->header();
# import cgi variables
my $action = $cgi->param('action') // ACTION_USER_TABLE;

my $message = "Please, make sure there aren't any users working with the software before performing update!";
my $title = "SYSTEM ADMINISTRATION";
$title = "ACCESS LEVEL ADMINISTRATION" if ($action =~ ACTION_USER_TABLE);
$title = "USER DETAIL ADMINISTRATION" if ($action =~ ACTION_USER_DETAIL);

if ($action !~ ACTION_LOGIN && !init_supersession()) {

    view_top();
    &view_msg("SUPER ACCESS DENIED", "INVALID NAME, PASSWORD OR ACCESS LEVEL!");
    $session->delete();
    exit 0;
}

# make sure user gets the login page if unauthrozied
if (!$session->param("~logged-in")) {

    $session->delete();
    $action = ACTION_LOGIN;
}

view_top();

view_login(ACTION_PRODUCT) if ($action =~ ACTION_LOGIN);
view_logout() if ($action =~ ACTION_LOGOUT);

view_dbupdate(ACTION_DBUPDATE_SUBMIT) if ($action =~ ACTION_DBUPDATE);
dbupdate() if ($action =~ ACTION_DBUPDATE_SUBMIT);

view_fupdate(ACTION_FUPDATE_SUBMIT) if ($action =~ ACTION_FUPDATE);
fupdate() if ($action =~ ACTION_FUPDATE_SUBMIT);

view_product() if ($action =~ ACTION_PRODUCT);
view_table() if ($action =~ ACTION_USER_TABLE);
#view_user(1) if ($action =~ ACTION_USER_DETAIL);
view_user(0) && view_user(1) if ($action =~ ACTION_USER_DETAIL);
update_user_access() if ($action =~ ACTION_USER_ACCESS);
update_user_password() if ($action =~ ACTION_USER_PASSWORD);
create_user() if ($action =~ ACTION_USER_CREATE);
delete_user() if ($action =~ ACTION_USER_DELETE);

view_bottom();

DBH::db_disconnect();# disconnect from database

exit 1;


################################################################################
# UTILITY FUNCTIONS
################################################################################

sub init_supersession {

    if ($session->param("~logged-in")) {
        return 1;  # if logged in, don't bother going further
    }

    my $user = $cgi->param('user') or return 1;
    my $password = $cgi->param('password') or return 1;

    # if we came this far, user did submit the login form
    # so let's try to load his/her profile if name/psswds match
    #if (auth_userr($user, $password)) {
    if (DBH::auth_superuser($user, $password)) {
        $session->expire(DBH::SUPERSESSION_EXPIRATION);
        $session->param("~user", $user);
        $session->param("~logged-in", 1);
        return 1;
    }

    return 0;
}

sub auth_user_deprecated($$) {

    my ($user, $password) = @_;

    my $result = DBH::db_select_row("SELECT * FROM USERS WHERE USER = \'$user\'");	
    my $authorized = DBH::db_select_array("SELECT COUNT(*) FROM USERS WHERE USER = \'$user\' AND PASSWORD = MD5(\'$password\')");

    if ( ($authorized) && ($result->{ADMIN} == 1) ) {
        #print STDERR "User $user authorized with password $password\n";
        return 1;
    } else {
        #print STDERR "User $user NOT authorized with password $password\n";
        return 0;
    }
}

sub view_login($) {

    $action = shift;
    $PAGE_LOGIN->param(ACTION => $action);
    print $PAGE_LOGIN->output;
}

sub view_top {

    $PAGE_TOP->param(ACTION_LOGOUT => ACTION_LOGOUT);
    $PAGE_TOP->param(ACTION_DBUPDATE => ACTION_DBUPDATE);
    $PAGE_TOP->param(ACTION_FUPDATE => ACTION_FUPDATE);
    $PAGE_TOP->param(ACTION_USERS => ACTION_USER_TABLE);
    $PAGE_TOP->param(ACTION_PRODUCT => ACTION_PRODUCT);
    $PAGE_TOP->param(TITLE => $title);

    print $PAGE_TOP->output;
}

sub view_bottom {

    $PAGE_BOTTOM->param(MESSAGE => $message);
    print $PAGE_BOTTOM->output;

}

sub view_msg($$) {

    my ($title, $msg) = @_;

    $PAGE_MSG->param(TITLE => $title);
    $PAGE_MSG->param(MESSAGE => $msg);

    print $PAGE_MSG->output;
}

sub view_product {

    my $result = DBH::db_select_row("SELECT * FROM PRODUCT");
    my $result2 = DBH::db_select("SELECT * FROM USERS");

    $PAGE_PRODUCT->param(PRODVER => $result->{PRODVER});
    $PAGE_PRODUCT->param(DBVER => $result->{DBVER});
    $PAGE_PRODUCT->param(DBDATE => $result->{DBDATE});
    $PAGE_PRODUCT->param(IMGVER => $result->{IMGVER});
    $PAGE_PRODUCT->param(IMGDATE => $result->{IMGDATE});
    $PAGE_PRODUCT->param(LICNAME => $result->{LICNAME});
    $PAGE_PRODUCT->param(LICUSR => $result->{LICUSR});
    $PAGE_PRODUCT->param(LICUSED => scalar(@$result2));
    $PAGE_PRODUCT->param(LICDATE => $result->{LICDATE});

    print $PAGE_PRODUCT->output;

}

sub view_user($) {

    my $option = shift // 1;
    my $user = $cgi->param('user');
    my $action = ACTION_USER_PASSWORD;
    my $message = 'modify user password';
    my $usereadonly = 'readonly';
    if ($option == 0) {
        $user = '';
        $action = ACTION_USER_CREATE;
        $message = 'create new user';
        $usereadonly = '';
    }

    $PAGE_USER->param(MESSAGE => $message);
    $PAGE_USER->param(USER => $user);
    $PAGE_USER->param(USEREADONLY => $usereadonly);
    $PAGE_USER->param(PASSWORD => '');
    $PAGE_USER->param(ACTION => $action);

    print $PAGE_USER->output;
}

sub view_table {

    my $user_data = DBH::db_select("SELECT * FROM USERS");

    my @loop1;
    foreach my $result ( @$user_data ) {

        my $admin = $result->{ADMIN};
        
        my %row = (
            ID       => $result->{ID},
            USER     => $result->{USER},
            LOCKED   => $result->{LOCKED} ? "checked" : "",
            ACTIVE   => $result->{ACTIVE} ? "checked" : "",
            ADROW    => $admin, # ? "checked" : "",
            ADMIN    => $admin & DBH::control('ADM') ? "checked" : "",
            ADBGN    => $admin & DBH::control('BGN') ? "checked" : "",
            ADCAD    => $admin & DBH::control('CAD') ? "checked" : "",
            ADCHF    => $admin & DBH::control('CHF') ? "checked" : "",
            ADDKK    => $admin & DBH::control('DKK') ? "checked" : "",
            ADUSD    => $admin & DBH::control('USD') ? "checked" : "",
            ADTRY    => $admin & DBH::control('TRY') ? "checked" : "",
            ADEUR    => $admin & DBH::control('EUR') ? "checked" : "",
            ADGBP    => $admin & DBH::control('GBP') ? "checked" : "",
            ADNOK    => $admin & DBH::control('NOK') ? "checked" : "",
            ADRUB    => $admin & DBH::control('RUB') ? "checked" : "",
            ADB11    => $admin & DBH::control('B11') ? "checked" : "",
            ADB12    => $admin & DBH::control('B12') ? "checked" : "",
            ADB13    => $admin & DBH::control('B13') ? "checked" : "",
            ADB14    => $admin & DBH::control('B14') ? "checked" : "",
            ADFOX    => $admin & DBH::control('FOX') ? "checked" : "",
            CURRENCY => $result->{CURRENCY},
            CREATED  => $result->{CREATED},
            LOGGED   => $result->{LOGGED},
            SESSIONS => $result->{SESSIONS},
            ACTUP    => ACTION_USER_ACCESS,
            ACTDEL   => ACTION_USER_DELETE,
            ACTDET   => ACTION_USER_DETAIL );

        push(@loop1, \%row);
    }

    $PAGE_TABLE->param(LOOP_1 => \@loop1);
    print $PAGE_TABLE->output;
}

sub view_users_is_now_deprecated { # see view_table

    my $results1 = DBH::db_select("SELECT * FROM USERS");

    my @loop1;
    foreach my $result ( @$results1 ) {

        my %row = (
            ID       => $result->{ID},
            USER     => $result->{USER},
            LOCKED   => $result->{LOCKED} ? "checked" : "",
            ACTIVE   => $result->{ACTIVE} ? "checked" : "",
            ADMIN    => $result->{ADMIN} ? "checked" : "",
            CURRENCY => $result->{CURRENCY},
            CREATED  => $result->{CREATED},
            LOGGED   => $result->{LOGGED},
            SESSIONS => $result->{SESSIONS}
            );

        push(@loop1, \%row);
    }

    $PAGE_TABLE->param(LOOP_1 => \@loop1);

    print $PAGE_TABLE->output;

}

sub view_logout() {

    my $user = $session->param("~user");
    $session->delete();
    DBH::db_update_column('ACTIVE', 0, $user);

    $PAGE_LOGOUT->param(USER => $user);
    print $PAGE_LOGOUT->output;
}

sub view_fupdate($) {

    my $action = shift;
    $PAGE_FUPDATE->param(ACTION => $action);
    print $PAGE_FUPDATE->output;
} 

sub view_dbupdate($) {

    my $action = shift;
    $PAGE_DBUPDATE->param(ACTION => $action);
    print $PAGE_DBUPDATE->output;
}

sub save_users {

    my @items = param('hristo');
    foreach my $item (@items) {
    }   

}

sub fupdate {

    # to do
    return;
}

sub dbupdate { # we can send sql scripts to the database

    my $db_user = $cgi->param('user');
    my $db_passwd = $cgi->param('password');
    my $db_file = $cgi->param('sqlfile');

    my $upload_dir = "/tmp";
    my $upload_filehandle = $cgi->upload('sqlfile');

    # dump stream to file
    my $update_file = "$upload_dir/$db_file";
    open (UPLOADFILE, ">$update_file") or die "$!";
    binmode UPLOADFILE;
    while (<$upload_filehandle>) { print UPLOADFILE; }
    close UPLOADFILE;

    # call mysql to import data
    system("/usr/bin/mysql --user=$db_user --password=$db_passwd CURRENCY < $update_file");

    if ($? != 0)  {
        view_msg("UPDATE", "ERROR ($?) WHILE UPDATING!");
    }

    unlink("$update_file");

    view_msg("UPDATE", "DATA SUCCESSFULLY UPDATED!");
}

sub update_user_password {

    my $user = $cgi->param('user');
    my $pass = $cgi->param('password');    
    if ($user && $pass) {

        $message = DBH::db_update("UPDATE USERS SET PASSWORD = MD5(\'$pass\') WHERE USER LIKE \'$user\'");
        view_msg("CHANGE USER PASSWORD", "USER $user PASSWORD IS CHANGED");
    } else {

        $message = 'update user password aborted - input not good - try again';
        view_user_detail(1);        
    }
}

sub update_user_access {

    my $user = $cgi->param('user');
    my $admin = 0;
    my %code = DBH::control('all');
    while( my ($clef, $value) = each(%code) ) {

        $admin += $cgi->param($clef) ? $value : 0;
    }

    $message = DBH::db_update_column('ADMIN', $admin, $user);
    view_user_table();
}

sub create_user {

    my $user = $cgi->param('user');
    my $pass = $cgi->param('password');
    if ($user && $pass) {

        $message = DBH::db_insert($user, $pass);
        view_user_table();
    } else {

        $message = 'create new user aborted - input not good - try again';
        view_user_detail(0);
    }
}

sub delete_user {

    my $user = $cgi->param('user');
    if ($user) {

        $message = DBH::db_delete($user);
    } else {

        $message = 'warning: user not defined';
    }

    view_user_table();
}

